backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "_data/menu"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "menu-item"}
      - {label: "Category", name: "category", widget: "select", options: ["Tacos & Antojitos", "Platos Principales", "Bebidas"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "about"
    label: "About Section"
    folder: "_data/about"
    create: true
    slug: "index"
    files:
      - file: "_data/about/index.md"
        label: "About Content"
        name: "about"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}

  - name: "location"
    label: "Location Information"
    folder: "_data/location"
    create: true
    slug: "index"
    files:
      - file: "_data/location/index.md"
        label: "Location Content"
        name: "location"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "location"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "City", name: "city", widget: "string"}
          - {label: "State", name: "state", widget: "string"}
          - {label: "Zip", name: "zip", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - label: "Hours"
            name: "hours"
            widget: "object"
            fields:
              - {label: "Monday - Thursday", name: "weekday", widget: "string"}
              - {label: "Friday - Saturday", name: "weekend", widget: "string"}
              - {label: "Sunday", name: "sunday", widget: "string"} 